version: 0.1
phases:
  install:
    commands:
      - npm install --only=prod
      - aws cloudformation package --template-file serverless.template --s3-bucket ${BUCKET_NAME} --output-template-file transformed-template.json
artifacts:
  type: zip
  files:
    - transformed-template.json
    - parameters.*.json